### ISSUE TITLE
A little bit curious about the radius of the cylinder reflector.

### ISSUE THREAD

**Issue by Dung-ND** [unlogical0327/RLA_V15_Implementation#2]
Hi,
I really want to know about the dimensions of the reflectors in your experiment, related to this set of data:
https://github.com/unlogical0327/RLA_V15_Implementation/blob/532a0ed6a85de7c427d107dc26c48e0e1956d9c6/LSF_xy.m#L5-L19

Could you disclose that information?
Thank you!

**Comment by unlogical0327** [comment]
just x, y and normalized intensity.

**Comment by Dung-ND** [comment]
Okay, I was just asking about the radius of the reflectors.

**Comment by unlogical0327** [comment]
actually, radius of reflectors doesn't matter in this case. It could be defined ahead and the location of reflector center doesn't depend on it.

**Comment by Dung-ND** [comment]
I implemented a part of your code in C++, and did some test with real reflectors. Last time I asked because I didn't have real data to test so want to see if my code was correct or not with your data.
I used Ceres solver to estimate the distance to reflector centers, that's why I asked about that radius. :D

Anyway, thank you for your work. Very helpful!

**Comment by unlogical0327** [comment]
hmm, I did have some laser scanner data for offline test but they are multi-mega size and hard to upload here. Let me know if u need some.

**Comment by Dung-ND** [comment]
Thanks for your offer. But I have already got the real equipment to test it out.

**Comment by unlogical0327** [comment]
great! 
you also can find more details in my paper from below link.
https://www.mdpi.com/1424-8220/21/13/4479/htm

**Comment by Dung-ND** [comment]
Already did. Thanks!
